### PR TITLE
ability to pull full spotifyd

### PR DESCRIPTION
**Pull request by andybaran**
I've been using this to build out a car computer using raspbian and had the need to use the "full" build of spotifyd.  I've added a few variables and some lines to the bash script to enable pulling either the full or slim builds and to always get the latest.

### CODE REVIEW

**Comment by nicokaiser** [comment]
Does the `full` version run properly in your setup? I had major problems getting it to start up, that's why I reverted the script to just use the `slim` version to maintain simplicity.

Using the full version would also enable the use of MPRIS (e.g. to display song titles via dbus), but I never got it running...

**Comment by andybaran** [comment]
I've been

> Does the `full` version run properly in your setup? I had major problems getting it to start up, that's why I reverted the script to just use the `slim` version to maintain simplicity.
> 
> Using the full version would also enable the use of MPRIS (e.g. to display song titles via dbus), but I never got it running...

I've been having to troubleshoot MPRIS as well and that's exactly what I was looking to get working.  I should have some more time to mess with it over the next few days and will let you the results.  I'd really like to have it working, it just opens up so many possibilities.

**Comment by andybaran** [comment]
I got tackled by a very large puppy with my Pi in my hands and  snapped the last SD card I have lying around :( It'll be a bit before I can resume testing for this.

**Comment by andybaran** [comment]
I have been able to test and it appears the full version is still not functional.  I'm keeping an eye on the spotifyd project though and will update here if it appears they've got it working.  cheers!

**Comment by nicokaiser** [comment]
I'll close this now, as spotifyd seems to have difficulties providing (even "lite") binaries, and I could not get MPRIS working at all.

**Comment by andybaran** [comment]
totally agree.

**Pull request closed without merging**
